### ISSUE TITLE
An archived XFSv4 filesystem should not be restored as an XFSv5

### ISSUE THREAD

**Issue by marcosfrm** [fdupoux/fsarchiver#1]
mkfs.xfs 3.2.3 enabled by default the new V5 format (`-m crc=1,finobt=1`). Current Sysrcd's default kernel (3.14) can not even mount the volume. It experimentally supports `-m crc=1` (stable upstream since 3.15), but not `-m finobt=1` (supported since 3.16, mkfs.xfs 3.2.1). To complicate things more, mkfs.xfs 4.2.0 also enabled by default `-n ftype=1` (supported since mkfs.xfs 3.2.0) for V4 volumes (ftype is madatory in V5).

`-m crc=0` (V4) with `-n ftype=1` is supported since kernel 3.13. And currently it breaks GRUB: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=768659 (but GRUB supports V5 just fine)

So FSArchiver needs at minimum always create XFSv4 file systems without ftype (`-n ftype=0` in case mkfs.xfs 4.2.0+ is used) until proper V5 support gets added.

See:
http://oss.sgi.com/pipermail/xfs/2015-November/045153.html
http://oss.sgi.com/pipermail/xfs/2015-December/045195.html
http://oss.sgi.com/pipermail/xfs/2015-December/045462.html

**Comment by marcosfrm** [comment]
Gmane threads:
http://thread.gmane.org/gmane.comp.file-systems.xfs.general/71385
http://thread.gmane.org/gmane.linux.debian.devel.bugs.general/1312795

**Comment by marcosfrm** [comment]
The problem happens in Sysrcd since xfsprogs was updated to 3.2.4.

**Comment by marcosfrm** [comment]
Sorry flood this report, but I think a logic like this would work for XFSv4-only FSArchiver:

```c
if (xfsprogs < 3.2.0)
    mkfs.xfs as it is today in fsarchiver
else if (xfsprogs >= 3.2.0)
    /* 3.2.1 and 3.2.2 do not enable crc by default, and ftype is not enabled
       either with -m crc=0 until 4.2.0, but this way we keep things simple */
    mkfs.xfs -m crc=0 -n ftype=0
fi
```

**Comment by fdupoux** [comment]
Thanks for your bug report. I have created a new git branch (xfsv5) in order to fix this issue. Basically it will detect the version of the filesystem during the savefs and create a new attribute called FSYSHEADKEY_FSXFSVERSION in the archive metadata. During the restore it will check the value of this attribute (it may be absent if the archive was created with an older fsarchiver version). So if this attribute is set to version 4 and a recent version of xfsprogs is installed, then it will add these extra options on the command line to create an XFS version 4 filesystem.

Can you please review the changes (it's actually just two commits which matter: a64830c and 7fc9367) to make sure the logic in the code makes sense to you, and to verify that it should work with the different versions of mkfs.xfs as there are different behaviors in the recent versions. Can you also test it (you will have to build it, I can provide a binary if necessary). You should use option -vv to print the extra XFS information.

I have also upgraded the standard kernel to the long-term supported linux-3.18 in SystemRescueCd-4.7.0 (currently in beta) so it is able to mount XFS v5 filesystems. But that's another project, we still need fsarchiver to be able to cope with distributions running old XFS versions.

**Comment by marcosfrm** [comment]
Thank you very much for looking into this. I will for sure test on the next few days.

For V4 images I think the logic is fine. For V5, mkfs.xfs 3.2.0-3.2.2, despite supporting it, does not enable crcs by default. FSArchiver needs to configure `-m crc=1` in this case, without `finobt=1` because 3.2.0 does not support it (3.2.3+ enables `-m finobt=1` by default). IOW:

```c
if (xfsprogs >= 3.2.0)
    /* 3.2.0-3.2.2 will set -m crc=1,finobt=0
       3.2.3+ will set -m crc=1,finobt=1 */
    mkfs.xfs -m crc=1
```

But before we get into that, there is another gotcha: because XFSv5 has its UUID stamped on every metadata block, V5 filesystems cannot have their UUID changed by xfs_admin until xfsprogs 4.2.0 and kernel 4.3 (when sb_meta_uuid was added). Once configured, it will set an incompatible superblock flag to prevent older kernels from mounting the fs.

http://oss.sgi.com/cgi-bin/gitweb.cgi?p=xfs/cmds/xfsprogs.git;a=commit;h=609f6bb20b7972c1a68370faea1dcbcf39912e07

http://oss.sgi.com/cgi-bin/gitweb.cgi?p=xfs/cmds/xfsprogs.git;a=commit;h=9c4e12fb60c15dc9c5e54041c9679454b42cb23e
http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/fs/xfs?id=ce748eaa65f2e9392ba82726503c8d994ffd6393

If mkfs.xfs had an option to define UUID at filesystem creation it would solve the problem. With the advantage of keeping both UUIDs, internal and "visible", in sync (no incompat flag) and, thus, preserving compatibility with older kernels, 3.15+ (`-m crc=1,finobt=0`) or 3.16+ (`-m crc=1,finobt=1`). Such an option does exist (`-m uuid=<UUID>`). Unfortunately it was only added in mkfs.xfs 4.3.0.

http://oss.sgi.com/cgi-bin/gitweb.cgi?p=xfs/cmds/xfsprogs.git;a=commit;h=6af48b97f8ef7196e1303996995b3614dde24ec2

Is an option for FSArchiver require mkfs.xfs >= 4.3.0?

**Comment by fdupoux** [comment]
Thanks for your investigations. That's really useful to have all these details. Can you please create seperate issues for these different problems ? Let's fix one problem at a time. So the current issue can be about preserving compatibility with XFSv4: if the saved XFSv4 it should be restored as v4. When you can confirm these initial changes are working, I will merge that into master and then work on the other issues.

We can create at least a separate issue regarding the UUID issue, and probably another one for the management of XFSv5 features. The situation seems to be a bit complicated considering all the possible combinations based on various version of the kernel, mkfs.xfs, etc. Part of the changes are to capture more specific filesystem attributes during savefs, such as which of the new features are enabled and disabled. Then the restfs operation will have to do the best thing it can do based on these attributes saved in the archive (or absent if the archive was created with an old version), and based on the version of mkfs.xfs. It is possible for fsachiver to fail if it is not satisfied with the version of mkfs.xfs, but it is should be possible to accomodate the behaviors to do the best thing based on the circumstances. So if an old version of mkfs.xfs is installed it may be better to create a filesystem without the new features, and in general users can upgrade the features manually if necessary. So maybe the first thing to do will be to write pseudo-code to define what to do in which case, as you did in the current issue.

**Comment by marcosfrm** [comment]
OK.

I compiled 0.6.20-git (xfsv5 branch) on CentOS 7 and tried to restore an image created with 0.6.19 from another CentOS 7 install in XFSv4. Because CentOS's mkfs.xfs is 3.2.2, which still creates XFSv4 by default, I also compiled and installed xfsprogs 4.3.0.

It is not working:

```
Detected fileformat=2 in archive /mnt/centos7.fsa
Current fsarchiver version: 0.6.20.0
Minimum fsarchiver version for that archive: 0.6.4.0
============= extracting filesystem 0 =============
Current fsarchiver version: 0.6.20.0
Minimum fsarchiver version for that filesystem: 0.6.4.0
strdico_get_string(dicocmdline, 'mkfsopt') doesn't exist
filesystem=[xfs]
filesystemoptions=[]
fsbytestotal=[7.99 GB]
fsbytesused=[876.11 MB]
getpathtoprog(mkfs.xfs)=[/usr/sbin/mkfs.xfs]
executing [mkfs.xfs -V]...
command [mkfs.xfs -V] returned 0
Detected mkfs.xfs version 4.3.0
getpathtoprog(mkfs.xfs)=[/usr/sbin/mkfs.xfs]
executing [mkfs.xfs -f /dev/sdc1    -b size=4096 ]...
command [mkfs.xfs -f /dev/sdc1    -b size=4096 ] returned 0
getpathtoprog(xfs_admin)=[/usr/sbin/xfs_admin]
executing [xfs_admin  -U 23aae3f3-6699-48af-9206-1807b31506b7  /dev/sdc1]...
command [xfs_admin  -U 23aae3f3-6699-48af-9206-1807b31506b7  /dev/sdc1] returned 0
Mount information: []
filesys.c#314,generic_mount(): partition [/dev/sdc1] cannot be mounted on [/tmp/fsa/20151229-192351-00] as [xfs] with options [nouuid]
oper_restore.c#1294,extractar_filesystem_extract(): partition [/dev/sdc1] cannot be mounted on /tmp/fsa/20151229-192351-00. cannot continue.

```

XFSv5 was created.

As a side note, xfs_admin only worked because it was >= 4.2.0 (incompat flag was set). Surprisingly this 3.10 heavy patched Red Hat kernel supports `-m crc=1,finobt=1` (but not sb_meta_uuid). Not relevant here though.

**Comment by fdupoux** [comment]
Thanks for your test. I have just pushed another commit (c13aea4) to change the behaviour of restfs when an archive has been created with an old version of fsarchiver as old versions do not store the FSXFSVERSION attribute. Now it will create an XFS v4 filesystem if this attribute cannot be found or if it can be found and it says the original filesystem was an XFS v4.

**Comment by marcosfrm** [comment]
Now it is working. 0.6.19 image:

```
Detected fileformat=2 in archive /mnt/centos7.fsa
Current fsarchiver version: 0.6.20.0
Minimum fsarchiver version for that archive: 0.6.4.0
============= extracting filesystem 0 =============
Current fsarchiver version: 0.6.20.0
Minimum fsarchiver version for that filesystem: 0.6.4.0
strdico_get_string(dicocmdline, 'mkfsopt') doesn't exist
filesystem=[xfs]
filesystemoptions=[]
fsbytestotal=[7.99 GB]
fsbytesused=[876.11 MB]
getpathtoprog(mkfs.xfs)=[/usr/sbin/mkfs.xfs]
executing [mkfs.xfs -V]...
command [mkfs.xfs -V] returned 0
Detected mkfs.xfs version 4.3.0
getpathtoprog(mkfs.xfs)=[/usr/sbin/mkfs.xfs]
executing [mkfs.xfs -f /dev/sdc1    -b size=4096  -m crc=0 -n ftype=0 ]...
command [mkfs.xfs -f /dev/sdc1    -b size=4096  -m crc=0 -n ftype=0 ] returned 0
getpathtoprog(xfs_admin)=[/usr/sbin/xfs_admin]
executing [xfs_admin  -U 23aae3f3-6699-48af-9206-1807b31506b7  /dev/sdc1]...
command [xfs_admin  -U 23aae3f3-6699-48af-9206-1807b31506b7  /dev/sdc1] returned 0
Mount information: []
partition [/dev/sdc1] was successfully mounted on [/tmp/fsa/20151230-072252-00] as [xfs] with options [nouuid]
```

And a XFSv4 fs saved with 0.6.20:

```
Detected fileformat=2 in archive /mnt/test.fsa
Current fsarchiver version: 0.6.20.0
Minimum fsarchiver version for that archive: 0.6.4.0
============= extracting filesystem 0 =============
Current fsarchiver version: 0.6.20.0
Minimum fsarchiver version for that filesystem: 0.6.20.0
strdico_get_string(dicocmdline, 'mkfsopt') doesn't exist
filesystem=[xfs]
filesystemoptions=[]
fsbytestotal=[7.99 GB]
fsbytesused=[876.42 MB]
getpathtoprog(mkfs.xfs)=[/usr/sbin/mkfs.xfs]
executing [mkfs.xfs -V]...
command [mkfs.xfs -V] returned 0
Detected mkfs.xfs version 4.3.0
getpathtoprog(mkfs.xfs)=[/usr/sbin/mkfs.xfs]
executing [mkfs.xfs -f /dev/sdc1    -b size=4096  -m crc=0 -n ftype=0 ]...
command [mkfs.xfs -f /dev/sdc1    -b size=4096  -m crc=0 -n ftype=0 ] returned 0
getpathtoprog(xfs_admin)=[/usr/sbin/xfs_admin]
executing [xfs_admin  -U 23aae3f3-6699-48af-9206-1807b31506b7  /dev/sdc1]...
command [xfs_admin  -U 23aae3f3-6699-48af-9206-1807b31506b7  /dev/sdc1] returned 0
Mount information: []
partition [/dev/sdc1] was successfully mounted on [/tmp/fsa/20151230-072645-00] as [xfs] with options [nouuid]
```

After restfs:

```
meta-data=/dev/sdc1              isize=256    agcount=4, agsize=524224 blks
         =                       sectsz=512   attr=2, projid32bit=1
         =                       crc=0        finobt=0
data     =                       bsize=4096   blocks=2096896, imaxpct=25
         =                       sunit=0      swidth=0 blks
naming   =version 2              bsize=4096   ascii-ci=0 ftype=0
log      =internal               bsize=4096   blocks=2560, version=2
         =                       sectsz=512   sunit=0 blks, lazy-count=1
realtime =none                   extsz=4096   blocks=0, rtextents=0

```

That is all as it should be.

I will open separate bugs for XFSv5 support.

**Comment by fdupoux** [comment]
Thanks. I have merged these changes into the master branch. So I will close this issue now, and we can focus on the next problem.

**Comment by marcosfrm** [comment]
Please put a comment explaining FSArchiver will always create V4 volumes without ftype.

https://github.com/fdupoux/fsarchiver/blob/8da9c77d5e9f577bae3824612766577aab126fe9/src/fs_xfs.c#L174

"XFSv4 + ftype=1 is supported since kernel 3.13. We purposely always disable ftype for V4 volumes to keep them compatible with older kernels" or so.

**Comment by fdupoux** [comment]
Good idea. I have added a comment about it.
