### ISSUE TITLE
fsarchiver rpm does not appear to be statically compiled

### ISSUE THREAD

**Issue by kneutron** [fdupoux/fsarchiver#104]
Downloaded latest fsarchiver so I could get zstd compression on MX18 / Debian stable and converted/installed rpm to .deb with alien, fsarchiver is still complaining about missing libs

REF: https://www.fsarchiver.org/installation/                                                    
# alien --to-deb fsarchiver-0.8.6-1.el7.x86_64.rpm
fsarchiver_0.8.6-2_amd64.deb generated

# dpkg -i fsarchiver_0.8.6-2_amd64.deb
Unpacking fsarchiver (0.8.6-2) over (0.8.1-1)

fsarchiver: error while loading shared libraries: libgcrypt.so.11: cannot open shared object file: No such file or directory

# apt install libzstd1 libzstd-dev zstd                                                                                                                   # apt install libcrypto++-dev libcrypto++-utils libgcrypt20-dev

 # whatprovides libgcrypt.so.11 ## apt-file search
Hit:1 http://security.debian.org stretch/updates InRelease
Hit:2 http://la.mxrepo.com/antix/stretch stretch InRelease                                                           
Hit:3 http://deb.debian.org/debian stretch-backports InRelease                                                       
Hit:4 http://mxrepo.com/mx/repo stretch InRelease                                              
Hit:5 http://ftp.us.debian.org/debian stretch-updates InRelease                                
Hit:6 https://download.virtualbox.org/virtualbox/debian stretch InRelease
Ign:7 http://ftp.us.debian.org/debian stretch InRelease
Hit:8 http://ftp.us.debian.org/debian stretch Release
(no results)

**Comment by kneutron** [comment]
Workaround: compiled fsarchiver from source with:

./configure --prefix=/usr --disable-gcrypt && time make -s && make install

**Comment by kneutron** [comment]
NOTE # apt install libbz2-dev lzma-dev liblz-dev liblzma-dev liblzo2-dev liblz4-dev e2fslibs-dev

**Comment by fdupoux** [comment]
The EL7 RPM is meant to be used on RHEL 7 and its clones. Please use the debian package on Debian.
