### ISSUE TITLE
I cannot restore an archive of a btrfs partition with two subvolumes to a new btrfs partition

### ISSUE THREAD

**Issue by ramanzes** [fdupoux/fsarchiver#108]
0)
> [root@fedora vs]# parted **/dev/sdb** print

Model: VMware, VMware Virtual S (scsi)
Disk /dev/sdb: 129GB
Sector size (logical/physical): 512B/512B
Partition Table: msdos
Disk Flags: 

Number  Start   End     Size    Type     File system  Flags
 1      1049kB  1075MB  1074MB  primary  ext4
 **2      1075MB  119GB   118GB   primary  btrfs**

________________________________________

0.1)

> [root@fedora vs]# `ls -s /mnt/sdd1`

total 49396396
      16 lost+found    267180 sdc3_btrfs_boot.fsa  **49129200 sdc3_btrfs_r_h.fsa**

0.2)

> [root@fedora vs]# parted **/dev/sdc** print

 
Model: VMware, VMware Virtual S (scsi)
Disk /dev/sdc: 1000GB
Sector size (logical/physical): 512B/512B
Partition Table: gpt
Disk Flags: 

Number  Start   End     Size    File system  Name                  Flags
 1      1049kB  630MB   629MB   fat32        EFI System Partition  boot, esp
 2      630MB   1704MB  1074MB  ext4
 **3      1704MB  120GB   118GB   btrfs**
 4      120GB   1000GB  880GB   ntfs                               msftdata

> fsarchiver savefs /mnt/sdd1/sdc3_btrfs_r_h.fsa **/dev/sdc3** -v -j 3

### not error/ all ok

---------------------------------------
### BUT NOW 
2)

> #fsarchiver restfs /mnt/sdd1/sdc3_btrfs_r_h.fsa id=0,dest=**/dev/sdb2** -v

_executing [mkfs.btrfs -f /dev/sdb2    -L 'fedora_localhost-live'  -U 'fb4bec6b-ce77-4fe1-8ace-e53dbd5721cf'  -s 4096 ]...
command [mkfs.btrfs -f /dev/sdb2    -L 'fedora_localhost-live'  -U 'fb4bec6b-ce77-4fe1-8ace-e53dbd5721cf'  -s 4096 ] returned 1
fs_btrfs.c#106,btrfs_mkfs(): command [mkfs.btrfs -f /dev/sdb2    -L 'fedora_localhost-live'  -U 'fb4bec6b-ce77-4fe1-8ace-e53dbd5721cf'  -s 4096 ] failed
oper_restore.c#1296,extractar_filesystem_extract(): **cannot make filesystem btrfs on partition /dev/sdb2_**

**why does not it work, because even the sizes of the partitions are the same ... what else is missing?**

**Comment by ramanzes** [comment]
> **Everything is fine. after shutting down the original disk from vmware (/dev/sdc). Because it is impossible to create a partition with the same UUID as on another disk**

**Comment by ramanzes** [comment]
This does not work, the subvolumes remain tied to the old disk. attempting to mount them from the root of the target partition mounts a subvolume of the (source) block device. Somewhere there is a binding ... Without the original disk, nothing happens at all in this case.

**Comment by marcosfrm** [comment]
Please use proper markdown "code" blocks: put command output between \```blabla\```.

Second, use `findmnt -u /mountpoint`.

Last time I tested Btrfs in FSArchiver, subvolumes were saved as plain directories...

**Comment by marcosfrm** [comment]
I could not make it work. `btrfs.ko` is very picky about mounting devices with same UUID. I think the only solution is restfs' `uuid=` option to create a new one:

```
newuuid=$(uuidgen)
fsarchiver restfs foo.fsa id=0,dest=/dev/sdx1,uuid=$newuuid
```

Then you mount the partition and if necessary configure stuff that requires the UUID using `$newuuid`.

**Comment by fdupoux** [comment]
Btrfs uses UUID to identify the different physical volumes which belong to the same logical file system, so it is not possible to copy btrfs file systems when it causes multiple btrfs file system to have to same UUID on the same machine. This is expected, and hence I confirm you have to make sure different file systems will have different UUIDs.
