### ISSUE TITLE
How do you specify which sub volume to save with BTRFS ?

### ISSUE THREAD

**Issue by sreyan32** [fdupoux/fsarchiver#109]
I am trying to backup my data using fsarchiver so that I can move back to ext4 from btrfs.

But the problem is that **I don't want all subvolumes to be saved.** 

**I just want to save a particular subvolume, how do I do that ?**

**Comment by marcosfrm** [comment]
Try changing the _default_ subvolume before running fsarchiver:

```
mount /dev/sdxy /mnt
btrfs subvolume set-default …
umount /mnt
fsarchiver savefs foo.fsa /dev/sdxy
```

See `man 8 btrfs-subvolume`.
