### ISSUE TITLE
Backup interruption caused by lstat64

### ISSUE THREAD

**Issue by yt-zgl** [fdupoux/fsarchiver#118]
If a file is deleted during the backup process, the whole process will be interrupted. It is recommended to add -- ingore_error option allows the backup to continue.
Because some unimportant files do not affect the backup of the whole file system.

error-info：
[errno=2, No such file or directory]: oper_save.c#781,createar_save_directory(): cannot lstat64(/tmp/fsa/20220401-112913-00049326-01/usr/users/cc/secun/SECDATASAVE1089)
oper_save.c#1332,oper_save(): archive_filesystem(/dev/mapper/vg01-lv03) failed
removed /dt/ct2.fsa
Line781 ，here：
    // ---- get details about current file
        if (lstat64(fullpath, &statbuf)!=0)
        {   sysprintf("cannot lstat64(%s)\n", fullpath);
            ret=-1;
            goto backup_dir_err;
        }

**Comment by marcosfrm** [comment]
Perhaps do not fail when `-A` is specified? With `-A` assume user knows what is doing, print the warning and continue...
