### ISSUE TITLE
QT FSArchiver Selecting wrong drive in Clone function

### ISSUE THREAD

**Issue by pbouthil** [fdupoux/fsarchiver#121]
FSArchiver is selecting the wrong hard drive under the Clone hard drive function. I select sda on the Exist harddrive column and then select sde in the New Harddrive column and then click Clone Harddrive the pop up Note screen shows that it will execute the command on sdd. I have attached a screenshot. This started to happen when I installed an ePCI USB 3.0 card in the PC. I am running Ubuntu Server 20.04.4 LTS OS with LXDE.
![image](https://user-images.githubusercontent.com/5903893/175426038-9d018c4d-8d25-4ada-85dc-beeb8fd2d70f.png)

**Comment by marcosfrm** [comment]
`fsarchiver` code has nothing to do with this. Report it to qt-fsarchiver:

https://github.com/DieterBaum/qt-fsarchiver
