### ISSUE TITLE
NTFS3 support?

### ISSUE THREAD

**Issue by a13xie** [fdupoux/fsarchiver#123]
Hi, I recently had to use `fsarchiver` for migrating Windows to an SSD for someone. I noticed all the warnings and disclaimers about NTFS support being experimental. When saving the archive I even had files with errors, so I think those warnings are justified :) I don't know if that backup will even boot, but we'll see.

To my point now. I noticed `fsarchiver` uses NTFS-3G as its "driver" for accessing and creating NTFS filesystems. I know NTFS-3G has many issues (mainly performance). Since Linux 5.15, a kernel driver called NTFS3 has been merged. I was wondering if using that instead of NTFS-3G could help with the speed but mainly reliability of `fsarchiver` on NTFS.

**Comment by fdupoux** [comment]
No there is no plan to add support for NTFS at this stage, it would take a lot of effort.

**Comment by tuxslack** [comment]
**Waiting for NTFS support.**

I want to test fsarchiver on Windows 11.


https://github.com/tuxera/ntfs-3g/
