### ISSUE TITLE
Restore files and/or directories from an image backup

### ISSUE THREAD

**Issue by mickpf** [fdupoux/fsarchiver#128]
Dear Sirs,

Is it technically possible to restore individual files or directories to any location from an image backup of a device/partition?

Is there a plan to implement that?

Kind Regards,
Michael

**Comment by mbiebl** [comment]
There is a related PR #77

**Comment by mickpf** [comment]
Hello,

well, that pull request is three years old, but this function is not implemented yet.

Kind Regards,
Michael

**Comment by vorwd** [comment]
@mickpf , you can take the edited code of the PR, edit the files in a clone of the repository, build from source, and BOOM, implimented :)
