### ISSUE TITLE
Is fsarchiver considered stable/reliable?

### ISSUE THREAD

**Issue by rjames777** [fdupoux/fsarchiver#14]
I attempted to register with the fsarchiver board but never got the confirmation e-mail, so was unable to post this question there.  

I would like to utilize this program, given it's wide range of stated capabilities.  I have used it and tested it for some basic save/restore operations, but concerned about the lack of activity on the community forum. Is the author actively supporting it? 

Thanks in advance.

**Comment by fdupoux** [comment]
Yes it is considered stable for linux filesystems such as ext4 and xfs but unstable for ntfs.

**Comment by marcosfrm** [comment]
@fdupoux 

Man page says:

> fsarchiver is still in development, don't use it for critical data yet.

Fits better:

> fsarchiver is considered stable for linux filesystems such as ext4 and xfs but unstable for ntfs.

**Comment by fdupoux** [comment]
You are right, it needs updating. Can you create a pull request for this change ?
