### ISSUE TITLE
cpp.patch

### ISSUE THREAD

**Issue by Rudlandh** [fdupoux/fsarchiver#16]
Hi, I put a patch on the results of testing your application via cppcheck

[cppcheck.patch.txt](https://github.com/fdupoux/fsarchiver/files/310630/cppcheck.patch.txt)

**Comment by fdupoux** [comment]
Thanks for the patch. Changes have been merged in the following Pull Request:
https://github.com/fdupoux/fsarchiver/pull/17
Most memory fixes have been implemented but the last one is invalid:
blkinfo->blkdata still refers to the buffer so if you call free(bufcomp) then blkinfo->blkdata will point to an area which has been de-allocated but is likely to contain the correct data by accident.
