### ISSUE TITLE
I continue view your code using cppcheck,

### ISSUE THREAD

**Issue by Rudlandh** [fdupoux/fsarchiver#18]
Hi, I continue view your code using cppcheck, this is the place in doubt - it will never be fulfilled:

file archwriter.c:
line 193:
"
if (wb->size <=0)
    {   errprintf("wb->size=%ld\n", (long)wb->size);
        return -1;
    }
"
wb->size - is unsigned value (u64), and it will never be less than 0. 

There's something wrong

**Comment by Rudlandh** [comment]
devinfo.c
line 91
      ((outdev->devsize=lseek64(fd, 0, SEEK_END))<0) ||

The unsigned variable '=' will never be negative so it is either pointless or an error to check if it is.

Attached is a list of all "suspicious" transactions
[fsarchiver.txt](https://github.com/fdupoux/fsarchiver/files/321934/fsarchiver.txt)

**Comment by fdupoux** [comment]
The test should just be "(wb->size == 0)" instead of "(wb->size <=0)"

**Comment by fdupoux** [comment]
I have fixed errors reported by cppcheck when it makes sense to do so. Sometimes it is better to leave the code as it is. Many scenarios such as arrayIndexOutOfBounds cannot happen and the conditions are actually difficult for a program to understand. Sometimes the errors reported do not exist (adding a free(bufcomp) in thread_comp.c would free memory which is passed to another function via another pointer),
