### ISSUE TITLE
About FAT mount options

### ISSUE THREAD

**Issue by marcosfrm** [fdupoux/fsarchiver#28]
Does `iocharset=foo`/`utf8` mess [1] affect FSArchiver 0.8.0+?

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=833238

IOW, does it need to pass any _safe_ mount options to generic_mount() in vfat_mount()?

[1] Debian's default is `iocharset=utf8`. In Ubuntu is `iocharset=iso8859-1`. Fedora OTH uses `iocharset=ascii`...

**Comment by fdupoux** [comment]
At the moment fsarchiver uses mount vfat filesystems without any particular options. According to this bug report it behaves much better with "utf8,iocharset=ascii" mount options so I would be tempted to use these. But not really sure what the best options are to be honest. I wonder if these options could make it fail when the kernel is not compiled with the right options for example.

**Comment by fdupoux** [comment]
I will leave the code as it is at the moment with no mount options and we can change it later if necessary if there is evidence of a better choice.

**Comment by marcosfrm** [comment]
@fdupoux Can you enable `CONFIG_FAT_DEFAULT_UTF8` in SystemRescueCd kernel? It makes `utf8` mount option default for FAT filesystems.
