### ISSUE TITLE
static i386 binaries

### ISSUE THREAD

**Issue by jniggemann** [fdupoux/fsarchiver#31]
Thank you for your great work on fsarchiver!
0.6.22 seems to be the latest version that has a static i386 download on github, would it be possible that you re-start to include i386 binaries in future releases?

I reckon that there aren't many 32bit  systems left, but there are still some :-)

**Comment by fdupoux** [comment]
Thanks for this bug report. I have just added 32bit static binaries for all recent versions

**Comment by jniggemann** [comment]
Great, thank you very much for your friendly and quick response and help!
