### ISSUE TITLE
print ~ remaining time ?

### ISSUE THREAD

**Issue by eoli3n** [fdupoux/fsarchiver#38]
I just discover that good project.
I was using tar | pv | xz > file, but your solution is more flexible.
Problem is that, it seems not possible to print a progress bar and remaining time, which pv does.
fsarchiver -v is ok for seeing "%", but as i want to compress xz-9 a heavy FS, remaining time is important to me (~ 3h).

**Comment by eoli3n** [comment]
without any comment ?

**Comment by fdupoux** [comment]
Sorry there are lot of work that can be done to improve fsarchiver but there is just no plan to work on any new feature at the moment, just stabilization and minor changes

**Comment by eoli3n** [comment]
ok, thx
