### ISSUE TITLE
RFE: EXT4 new features

### ISSUE THREAD

**Issue by marcosfrm** [fdupoux/fsarchiver#41]
- Since e2fsprogs 1.43, `mke2fs` enables by default the `64bit` option. It was added around 1.40 (cannot find exactly when), but up to 1.41 it was buggy (http://marc.info/?l=linux-ext4&m=121607919430525&w=2). So `-O 64bit` was not recommended until 1.42 (http://marc.info/?l=linux-ext4&m=127652278706450&w=2), which also enabled the feature automatically if the filesystem being created was bigger than 16 TiB (`auto_64-bit_support = 1` in `/etc/mke2fs.conf`). FSArchiver needs to respect this setting at restore now that is going to be used much more often on < 16 TiB volumes.

- Since kernel 3.5, EXT4 supports metadata checksumming (considered stable starting with 3.18<sup>[1]</sup>), in a similar way as XFSv5. Userspace support exists since e2fsprogs 1.43 (`-O metadata_csum`).

When `metadata_csum` is enabled, changing UUID with `tune2fs` in a heavy populated fs is slow, as it needs to walk through filesystem metadata. This can be avoided using the `-U <uuid>` option introduced in mke2fs 1.41.4<sup>[2]</sup> to set UUID at filesystem creation. FSArchiver is not affected by this problem, because it changes the UUID on fresh new empty fs, but `-U <uuid>` at mkfs time is more elegant though.

Superblock flags are:

EXT4_FEATURE_INCOMPAT_64BIT
EXT4_FEATURE_RO_COMPAT_METADATA_CSUM

<sup>[1]</sup> https://git.kernel.org/pub/scm/fs/ext2/e2fsprogs.git/commit/?id=210baa5d8a58f84ab12772e80a839a4e74a54134
<sup>[2]</sup> https://git.kernel.org/pub/scm/fs/ext2/e2fsprogs.git/commit/?id=b0afdda1bc044026336009576fbe6b72884140cb

**Comment by marcosfrm** [comment]
Ooops, as per

https://git.kernel.org/pub/scm/fs/ext2/e2fsprogs.git/commit/?id=9aef4b695445c0bc12a79b8c0bd68efc194302e7

we should require 1.42.10 to use `-O 64bit`.

**Comment by marcosfrm** [comment]
There is one scenario I am not sure how FSArchiver should deal with: one has a non-64bit EXT4 archive and will restore it on > 16 TiB device.

If `mke2fs -O ^64bit` runs on a > 16 TiB device it will fail. On the other hand, if we upgrade it to `-O 64bit`, GRUB/kernel compatibility may break, but at least restfs will work.

```
         |            RESTFS               |
 ARCHIVE +----------------+----------------+
         |  DEV < 16 TiB  |  DEV > 16 TiB  |
---------+----------------+----------------+
  64bit  |      64bit     |      64bit     |
---------+----------------+----------------+
 ^64bit  |     ^64bit     |   -> 64bit <-  |
---------+----------------+----------------+
```

**Comment by marcosfrm** [comment]
More precisely, the 16 TiB limit is block size dependent: `2^32 * 4k`.

**Comment by marcosfrm** [comment]
I did some tests and 1.41.x does **not** have `64bit` support at all. It will always fail on devices > `2^32 * block_sz`.


```
         |                      RESTFS                        |
 ARCHIVE +------------------------+---------------------------+
         | DEV < 2^32 * block_sz  |   DEV > 2^32 * block_sz   |
---------+------------------------+---------------------------+
         |  if mke2fs >= 1.42     |  if mke2fs >= 1.42        |
         |      64bit             |      64bit                |
         |  else                  |  else                     |
  64bit  |      nothing           |      fail                 |
---------+------------------------+---------------------------+
         |  if mke2fs >= 1.42     |  if mke2fs >= 1.42        |
         |      ^64bit            |      64bit + user warning |
         |  else                  |  else                     |
 ^64bit  |      nothing           |      fail                 |
---------+------------------------+---------------------------+
```

1.42 is enough if **when device is > `2^32 * block_sz`** (we will always use `-O 64bit`) an eventual `resize_inode` is changed to `^resize_inode`. Version 1.42.10+ does this by default.

**Comment by marcosfrm** [comment]
Two more:

EXT4_FEATURE_COMPAT_SPARSE_SUPER2 --> `-O sparse_super2` (since e2fsprogs 1.42.10)
EXT4_FEATURE_INCOMPAT_INLINE_DATA --> `-O inline_data` (since e2fsprogs 1.43)

**Comment by marcosfrm** [comment]
Clarifying: this issue is not just RFE, but also a bugfix to support volumes bigger than 16 TiB with EXT4 (particularly when original filesystem had `64bit` set). The other features (`metadata_csum`, `sparse_super2`, `inline_data`) are indeed *enhancements*  :) .

**Comment by fdupoux** [comment]
Thanks for your research regarding ext4 features. Why don't you make a pull request ? You contributed good changes to improve the xfs features, why not do the same again with ext4 ?

**Comment by marcosfrm** [comment]
My programming skills are minimal. :( A true programmer must pick this one. I can as always test the changes.

**Comment by fdupoux** [comment]
The "man ext4" manual page also shows there is a "project" feature, and it has been supported since e2fsporgs-1.43 according to this changelog:
http://e2fsprogs.sourceforge.net/e2fsprogs-release.html

**Comment by fdupoux** [comment]
I have pushed a new "ext4features" where I have basically updated the definition of the list of features. It should be sufficient in order to preserves these features. Can you check if the changes make sense (in term of e2fsprogs version required for example) and if they work as expected ?

I have not added any additional logic. If we think additional logic will be required to enable or disable specific features or do additional checks, we can consider it next.

**Comment by FuturePilot** [comment]
I see it has 64bit. Could you also add metadata_csum as well? That also seems to be default for mke2fs on recent distros.

**Comment by fdupoux** [comment]
Thanks @FuturePilot I have updated the new branch with support for the "metadata_csum" feature. Testing is welcome

**Comment by FuturePilot** [comment]
Thanks! I will test this soon and report back.

**Comment by FuturePilot** [comment]
Looks like it worked as expected.

`============= extracting filesystem 0 =============
executing [mke2fs -V]...
command [mke2fs -V] returned 0
executing [mke2fs -V]...
command [mke2fs -V] returned 0
executing [mke2fs /dev/sdb1  -q  -F  -r 1    -b 4096  -I 256  -O has_journal,ext_attr,resize_inode,dir_index,^sparse_super2,filetype,extent,^journal_dev,flex_bg,^meta_bg,^mmp,64bit,^inline_data,large_file,huge_file,sparse_super,^uninit_bg,dir_nlink,extra_isize,^bigalloc,metadata_csum,^project ]...
command [mke2fs /dev/sdb1  -q  -F  -r 1    -b 4096  -I 256  -O has_journal,ext_attr,resize_inode,dir_index,^sparse_super2,filetype,extent,^journal_dev,flex_bg,^meta_bg,^mmp,64bit,^inline_data,large_file,huge_file,sparse_super,^uninit_bg,dir_nlink,extra_isize,^bigalloc,metadata_csum,^project ] returned 0`

Resulting filesystem has 64bit and metadata_csum
`Filesystem features:      has_journal ext_attr resize_inode dir_index filetype extent 64bit flex_bg sparse_super large_file huge_file dir_nlink extra_isize metadata_csum
Filesystem flags:         signed_directory_hash 
Default mount options:    user_xattr acl`

**Comment by fdupoux** [comment]
@FuturePilot Thanks for your test

**Comment by marcosfrm** [comment]
EXT4_FEATURE_INCOMPAT_BG_USE_META_CSUM does not exist anymore:

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=8c81bd8f586c46eaf114758a78d82895a2b081c2

It was replaced by EXT4_FEATURE_INCOMPAT_CSUM_SEED. Cosmetics in `src/fs_ext2.h`. :-)

---

With devices bigger than `2^32 * block_sz` special logic is needed: archives saved without `64bit` will fail. Is it doable add a device size check for this? For XFS we downgrade the filesystem in some cases (old xfsprogs). In EXT4 we would be doing an upgrade...

Then there is the `resize_inode` bug between 1.42 and 1.42.9: when device is bigger than `2^32 * block_sz` (`64bit` is mandatory), mke2fs should disable `resize_inode` but fails to do it.

**Comment by marcosfrm** [comment]
BTW, such large 64-bit EXT4 filesystems without `uninit_bg` or `metadata_csum` (`metadata_csum` supersedes `uninit_bg`) will take several minutes to create. We could add another logic to flip `uninit_bg` on if `metadata_csum` is not set (or if `metadata_csum` is set but mke2fs < 1.43).

`uninit_bg` is supported since ages and is always available on mke2fs versions which support `64bit` (1.42+).

EXT is a mess.

**Comment by fdupoux** [comment]
I have added the logic to force the 64bit flag when the target device is larger than 2^32 blocks. You can test using option -vv to see the debugging messages which say how many blocks there are and related information.

**Comment by fdupoux** [comment]
Should we always disable the resize_inode feature on device with more than 2^32 blocks (whatever the e2fsprogs version) or is it necessary to check the e2fsprogs version ? It sounds it would not harm to always disable this feature on large devices and it would simplify to code if we do not have to check the e2fsprogs version.

**Comment by marcosfrm** [comment]
With devices equal to 2^32 blocks it fails too. This fixes it:

```diff
--- fs_ext2.c    2017-08-20 16:48:52.000000000 -0300
+++ fs_ext2.c    2017-08-20 17:39:13.913646806 -0300
@@ -268,10 +268,10 @@
     {   devblkcount=devsize/temp64;
         threshold64bit=(1LL<<32LL);
         msgprintf(MSG_VERB2, "the filesystem block size is %ld bytes long\n", (long)temp64);
-        msgprintf(MSG_VERB2, "the 64bit flag is required on devices larger than %lld blocks\n", (long long)threshold64bit);
+        msgprintf(MSG_VERB2, "the 64bit flag is required on devices equal or larger than %lld blocks\n", (long long)threshold64bit);
         msgprintf(MSG_VERB2, "device [%s] size is %lld bytes long\n", partition, (long long)devsize);
         msgprintf(MSG_VERB2, "device [%s] size is %lld blocks long\n", partition, (long long)devblkcount);
-        if (devblkcount > threshold64bit)
+        if (devblkcount >= threshold64bit)
         {   features_tab[E2P_FEATURE_INCOMPAT] |= FSA_EXT4_FEATURE_INCOMPAT_64BIT;
             msgprintf(MSG_VERB2, "device [%s] requires the 64bit flag to be enabled\n", partition);
         }
```

Yeah, I think we can always disable `resize_inode` when >= 2^32.

**Comment by fdupoux** [comment]
I have applied your fix and implemented more changes when the target device is large. Can you check if it is all ok ?

**Comment by marcosfrm** [comment]
`uninit_bg` and `metadata_csum` can be enabled at same time, because mke2fs 1.43+ will disable the former as needed.

https://git.kernel.org/pub/scm/fs/ext2/e2fsprogs.git/tree/misc/mke2fs.c?h=v1.43#n2299

So the logic is ok.

---

fsarchiver -vv says for EXT4:

> mke2fs version required: 1.41.0

Running mke2fs 1.41.x on big devices will fail. Users may be confused. Can you add a error message if e2fsprogs < 1.42 and device >= 2^32 blocks? Something like this:

> filesystem cannot be created without [64bit] flag on this device, e2fsprogs 1.42 or later is required

---

Then, just nitpicks:

https://github.com/fdupoux/fsarchiver/blob/ext4features/src/fs_ext2.c#L250

> // Special logic required if the target device is **equal or** more than 2^32 blocks long

https://github.com/fdupoux/fsarchiver/blob/ext4features/src/fs_ext2.c#L258

> without

https://github.com/fdupoux/fsarchiver/blob/ext4features/src/fs_ext2.c#L264

Please expand this comment:

> // If "metadata_csum" is enabled, mke2fs will disable "uninit_bg" automatically

**Comment by marcosfrm** [comment]
And of course if fsarchiver is about to create EXT2 or EXT3 on big devices, it must say only EXT4 supports them.

mke2fs error:

> Extents MUST be enabled for a 64-bit filesystem.  Pass -O extents to rectify.

**Comment by fdupoux** [comment]
Ok I have pushed other changes regarding your latest comments

**Comment by fdupoux** [comment]
I have made another change to make sure it will always check the size of the target device, even if the FSYSHEADKEY_FSEXTBLOCKSIZE attribute is not stored in the archive. It will use a block size of 4096 if attribute is absent. Previously the test was executed only if the original block size was known.

**Comment by marcosfrm** [comment]
It is working very well. Two nitpicks:

https://github.com/fdupoux/fsarchiver/blob/ext4features/src/fs_ext2.c#L269 : 64bit (no space)

https://github.com/fdupoux/fsarchiver/blob/ext4features/src/fs_ext2.c#L272 : missing new line

Thanks!

**Comment by marcosfrm** [comment]
Also replace in `src/fs_ext2.h` EXT4_FEATURE_INCOMPAT_BG_USE_META_CSUM with EXT4_FEATURE_INCOMPAT_CSUM_SEED (https://github.com/fdupoux/fsarchiver/issues/41#issuecomment-323538671).

**Comment by fdupoux** [comment]
Ok I have applied these last few minor changes. So is everything all good now ?

**Comment by marcosfrm** [comment]
Yes. :-)

**Comment by fdupoux** [comment]
Ok I have merged the changes to the master branch, and I have rewritten the commits to not mess up the git history too much with plenty of small changes. Many thanks for your investigation and your help
