### ISSUE TITLE
Resizing Google Compute instance disk to a smaller disk

### ISSUE THREAD

**Issue by nodesocket** [fdupoux/fsarchiver#42]
Hello.

I am trying to resize a Google Cloud disk to smaller, and think I should be able to accomplish using fsarchiver. Is it possible to run:

```
fsarchiver -A -a savefs /mnt/sdb/sda1.fsa /dev/sda1
````

Where `sda1` is the source disk, and `/mnt/sdb` is a secondary disk attached to the instance. Mainly, can I save the fs (`/dev/sda1`) that is the primary/boot and mounted?

Finally I will attach a 3rd disk _(`/dev/sdc` the final smaller disk)_ to the instance, and restore to it:

```
fsarchiver restfs /mnt/sdb/sda1.fsa id=0,dest=/dev/sdc
````

Will this process work?

**Comment by marcosfrm** [comment]
If `/dev/sda1` filesystem is supported by fsarchiver, it will work. As stated in the man page, backup of rw mounted devices is not ideal.

**Comment by nodesocket** [comment]
I tried this, and the Google Cloud instance failed to boot using the `fsarchiver` backup. Note, when I invoked `savefs` it prompted to set the flags `-A -a`.

Anything I might be missing? Would love to get this working?

**Comment by marcosfrm** [comment]
Note that fsarchiver creates the filesystem from scratch. You may need to reinstall the bootloader, if there is one.

**Comment by nodesocket** [comment]
Thanks, do you have a guide for this process by chance?

**Comment by marcosfrm** [comment]
What Linux is that? Debian, CentOS, etc?

**Comment by nodesocket** [comment]
@marcosfrm 

```
➜  /etc cat redhat-release
CentOS release 6.9 (Final)
```

**Comment by marcosfrm** [comment]
Based on

https://cloud.google.com/compute/docs/images/import-existing-image

you have a plain virtual hard disk, with MBR partition table, and `/dev/sda1` as root/boot filesystem.

You probably need to create a partition table on `/dev/sdc` (will erase everything on it!):

```
wipefs -a /dev/sdc
parted -s /dev/sdc -- mklabel msdos mkpart primary ext4 0% 100% set 1 boot on
wipefs -af /dev/sdc1
```

Now restore the archive to `/dev/sdc1`:

```
fsarchiver restfs /mnt/sdb/sda1.fsa id=0,dest=/dev/sdc1
```

And finally reinstall GRUB:

```
mount /dev/sdc1 /mnt
mount --bind /dev /mnt/dev
mount --bind /proc /mnt/proc
mount --bind /sys /mnt/sys
chroot /mnt grub-install /dev/sdc
umount /mnt/dev /mnt/proc /mnt/sys /mnt
```

**Comment by nodesocket** [comment]
@marcosfrm thanks for the detailed steps.

When running:

    ➜  ~ chroot /mnt grub-install /dev/sdc
    /dev/sdc does not have any corresponding BIOS drive.

Seeing that error though. Any ideas?

**Comment by marcosfrm** [comment]
Nope.  Take a look here:

http://forums.fedoraforum.org/showthread.php?t=214137

**Comment by nodesocket** [comment]
@marcosfrm didnt see anything useful in that thread.

I feel like I am super close. Just stuck on:

```
➜  ~ chroot /mnt grub-install /dev/sdc
/dev/sdc does not have any corresponding BIOS drive.
```

**Comment by nodesocket** [comment]
@marcosfrm here is a guide of all the steps I have completed thus far. Maybe you can spot the issue?

Attached two new persistent disks `(backup, new)` of the same size and desired size to existing instance. The first persistent disk `backup` stores the contents of the existing disk. The second persistent disk `new` is  the new disk you will use.

    original disk     /dev/sda1      (500 GB)
    backup disk     /dev/sdb        (100 GB)
    new disk          /dev/sdc        (100 GB)

Format and mount the`backup` disk:

    mkfs.ext4 -m 0 -F -E lazy_itable_init=0,discard /dev/sdb
    mkdir -p /mnt/sdb
    mount -o discard,defaults /dev/sdb /mnt/sdb

Stop any services or processes that write to the `original` disk. Examples include databases, web servers, caches, applications, etc.

Backup the `original` disk to the `backup` disk using `fsarchiver`.

    fsarchiver -A -a savefs /mnt/sdb/sda1.fsa /dev/sda1

Prepare the `new` disk:

    wipefs -a /dev/sdc
    parted -s /dev/sdc -- mklabel msdos mkpart primary ext4 0% 100% set 1 boot on
    wipefs -a /dev/sdc1

Restore `backup` to `new` disk:

     fsarchiver restfs /mnt/sdb/sda1.fsa id=0,dest=/dev/sdc1

Install grub on `new` disk:

    mount /dev/sdc1 /mnt/sdc
    mount --bind /dev /mnt/sdc/dev
    mount --bind /proc /mnt/sdc/proc
    mount --bind /sys /mnt/sdc/sys
    chroot /mnt/sdc grub-install /dev/sdc
    umount /mnt/dev /mnt/proc /mnt/sys /mnt/sdc
