### ISSUE TITLE
RFE: Add the option to validate the integrity of an archive file

### ISSUE THREAD

**Issue by lhernanz** [fdupoux/fsarchiver#44]
Hi,

Right now, the only way to validate that an archive is not corrupt is to try to restore it. It would be much better to have an option that would scan the file and validate the checksums without trying to restore the files. For archives that have been copied to different media or are going to be stored for a while before restoring, this would be a very handy option.

Thanks

Regards

**Comment by lhernanz** [comment]
Hi,

Apparently, someone contributed some code to make this possible a few years back:

http://forums.fsarchiver.org/viewtopic.php?f=22&t=987

Regards

**Comment by fdupoux** [comment]
These changes are not going to be merged in the near future as they modify the fsarchiver core and could introduce regressions. At the moment the focus is on stability and minor changes such as support for new filesystem features.
