### ISSUE TITLE
Update website to recognize support for FAT filesystem

### ISSUE THREAD

**Issue by BobCollins42** [fdupoux/fsarchiver#45]
I appreciate the addition of support (shown in the change log) for FAT (I assume FAT32) to support archives of disks that have an EFS (EFI file system). 

There are places on your site which don't list support for FAT, and in your FAQ, you expressly deny support for FAT. This should be updated.

BTW, FSArchiver's previous lack of support for the EFS caused me to look elsewhere for a solution last year.

**Comment by fdupoux** [comment]
Thanks the website has been updated:
https://github.com/fdupoux/fsarchiver/commit/747450574a615c1d63d270b9b7ff553e7cdfd2dd

BTW Pull requests for updating the website are welcome as the contents is now stored in git and the static HTML website is generated using hugo.
