### ISSUE TITLE
fsarchiver fails to build against new  attr 2.4.48

### ISSUE THREAD

**Issue by david-geiger** [fdupoux/fsarchiver#52]
Hi,

I tried to compile fsarchiver with latest  attr package version 2.4.48, but now it fails to build due to a missing include:

configure: error: attr/xattr.h not found. you may have to install a package called attr, libattr, libattr-devel
[fsarchiver_build_log.txt](https://github.com/fdupoux/fsarchiver/files/1696072/fsarchiver_build_log.txt)

**Comment by fdupoux** [comment]
Seems to be similar to https://bugs.gentoo.org/644048

**Comment by fdupoux** [comment]
@david-geiger Can you please check if Pull-Request #54 fixed your problem ?

**Comment by david-geiger** [comment]
Excellent! now fsarchiver build fine with your patch.

**Comment by fdupoux** [comment]
Thanks for having confirmed it works ok. I am now going to close this ticket

**Comment by gaurav-nelson** [comment]
thanks
