### ISSUE TITLE
doesn't handle btrfs subvolumes

### ISSUE THREAD

**Issue by 2011** [fdupoux/fsarchiver#79]
Ran fsarchiver on the device, and it only backed up the main volume, (none of the subvolumes). I would consider this very basic functionality.

**Comment by marcosfrm** [comment]
https://github.com/fdupoux/fsarchiver/blob/0.8.5/README#L39

**Comment by 2011** [comment]
> https://github.com/fdupoux/fsarchiver/blob/0.8.5/README#L39

I did see that before, but subvolumes and snapshots have nothing in common. Subvolumes do not represent any type of shared storage that can have multiple parents. They function almost as separate partitions. It requires no special tools to list and access them, and I believe that (as a very basic feature of btrfs) that fsarchiver should handle them.

**Comment by marcosfrm** [comment]
Well, subvolume is a feature _very specific to a filesystem_. Current FSArchiver **will** backup subvolumes as simple directories.

If you mean teach FSArchiver to _recreate_ the subvolumes, it will probably require non-trivial changes.

**Comment by fdupoux** [comment]
Specific file system features such as subvolumes are really beyond the scope of fsarchiver. Also btrfs send/receive tools may be more suitable to take advantage of btrfs.
