### ISSUE TITLE
Dual boot Ubuntu 15.10 systems needed boot-repair after a system restore.

### ISSUE THREAD

**Issue by totter** [fdupoux/fsarchiver#8]
Following one system restore, re-booted to find no menu, and a grub> prompt.
Boot-repair fixed it back to dual boot Ubuntu 15.10 systems.

Using two SSDs with a default install of primary system on first 128GB drive.  
Second SSD 256GB gparted into two.  
Installed Ubuntu 15.10 as maint system to first partition.  
Second partition used for .fsa backups of primary system.
Used fsarchiver in maint system to archive primary system. 
All worked fine, and dual boot still functional.
Used fsarchiver to restore primary system .fsa into maint system, intending to have two practically identical systems.
Booted to find no menu, and a grub> prompt.

Boot-repair fixed it back to dual boot Ubuntu 15.10 now practically identical systems.
So it all worked great, aside from the boot menu.

**Comment by marcosfrm** [comment]
If GRUB is installed on the partition this is expected. FSArchiver will recreate the file system with same UUID, mount it and put every data back keeping permissions, timestamps, xattrs, etc. There is no way to ensure GRUB files will be at same location as before for block lists work. If GRUB is installed on the MBR (actually on the MBR "gap" before first partition, assuming MSDOS partitioning), it should work.

**Comment by totter** [comment]
I'm new to Ubuntu, and just used a default install to the SSD:
/dev/sda1      fat32       /boot/efi
/dev/sda2      ext4        /
/dev/sda2      linux-swap
From your reply, if grub were in the sda1 fat32 partition, then it wouldn't have lost the boot menu.
I'm not sure where grub resides, but there is a /boot/grub folder in the sda2 ext4 partition.
So I guess grub resides on sda2, but the unchanged  sda1 /boot/efi  no longer finds it.
Which means I wouldn't be any better off archiving and restoring both sda1 and sda2.
Anyway, fsarchiver still provides a convenient system backup and restore process,  and it's not much extra to run boot-repair.
I also needed to assigned a new UUID with gparted, as two partitions with the same UUID can't be a good idea, and it confused boot-repair.
The boot-repair is not much inconvenience, but maybe a good fix would be to have a dedicated grub partition:  http://www.troubleshooters.com/linux/grub/grubpartition.htm
On reflection it looks like fsarchiver is performing as intended, but the boot process is rather less robust.

**Comment by marcosfrm** [comment]
UEFI is another history. I do not use GRUB with UEFI, but I *think* it puts on the EFI System Partition (/boot/efi) full core.img which allows it to find /boot/grub stuff reading the root file system (no blocklists).

But you cannot change UUIDs, because if you do so GRUB will stop working until you regenerate its config file.

**Comment by totter** [comment]
On 20/01/16 12:20, Marcos Mello wrote:
>
> UEFI is another history. I do not use GRUB with UEFI, but I /think/ it 
> puts on the EFI System Partition (/boot/efi) full core.img which 
> allows it to find /boot/grub stuff reading the root file system (no 
> blocklists).
>
> But you cannot change UUIDs, because if you do so GRUB will stop 
> working until you regenerate its config file.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/fdupoux/fsarchiver/issues/8#issuecomment-173187045>.
>
Yes, I forgot to mention Grub Customizer was needed after the UUID was 
changed.
