### ISSUE TITLE
I want to keep inodes size of partition.

### ISSUE THREAD

**Issue by NabiKAZ** [fdupoux/fsarchiver#84]
I use 0.8.5 (2018-07-10) version.
I want to keep inodes size of partition.
I try this command, but dont' effective.
Added `mkfsopt="-O ^resize_inode"` params.

```
[root@sysresccd ~]# fsarchiver restfs -vj8z0 file.fsa id=0,dest=/dev/sdb1,label=aaaaa,mkfsopt="-O ^resize_inode"
============= extracting filesystem 0 =============
executing [mke2fs -V]...
command [mke2fs -V] returned 0
executing [mke2fs -V]...
command [mke2fs -V] returned 0
executing [mke2fs /dev/sdb1  -q  -F  -O ^resize_inode  -b 4096  -L 'aaaaa'  -U 47849ac4-0cba-4fde-b7f0-0c22b159ad13  -I 256  -r 1  -O has_journal,ext_attr,resize_inode,dir_index,^sparse_super2,filetype,extent,^journal_dev,flex_bg,^meta_bg,^mmp,64bit,^inline_data,^ea_inode,^large_dir,large_file,huge_file,sparse_super,^uninit_bg,dir_nlink,extra_isize,^bigalloc,metadata_csum,^project ]...
command [mke2fs /dev/sdb1  -q  -F  -O ^resize_inode  -b 4096  -L 'aaaaa'  -U 47849ac4-0cba-4fde-b7f0-0c22b159ad13  -I 256  -r 1  -O has_journal,ext_attr,resize_inode,dir_index,^sparse_super2,filetype,extent,^journal_dev,flex_bg,^meta_bg,^mmp,64bit,^inline_data,^ea_inode,^large_dir,large_file,huge_file,sparse_super,^uninit_bg,dir_nlink,extra_isize,^bigalloc,metadata_csum,^project ] returned 0
executing [tune2fs /dev/sdb1  -o user_xattr,acl  -c 0  -i 0d ]...
command [tune2fs /dev/sdb1  -o user_xattr,acl  -c 0  -i 0d ] returned 0
Mount information: []
-[00][ 24%][DIR     ] /
-[00][ 49%][DIR     ] /lost+found
-[00][ 74%][DIR     ] /aaa
-[00][100%][REGFILEM] /file
Statistics for filesystem 0
* files successfully processed:....regfiles=1, directories=3, symlinks=0, hardlinks=0, specials=0
* files with errors:...............regfiles=0, directories=0, symlinks=0, hardlinks=0, specials=0

```

I find this line of codes:

https://github.com/fdupoux/fsarchiver/blob/9c02cbce5a90d9f6ea3be8787d37a7873bee29b0/src/fs_ext2.c#L58

**Comment by marcosfrm** [comment]
The inode size is preserved by the `-I 256` option (`FSYSHEADKEY_FSINODESIZE`).

I suppose you **do not** want  to preserve the `resize_inode` feature.

We can try to add `mkfsopt` arguments latter in `mke2fs` invocation:

https://github.com/fdupoux/fsarchiver/blob/9c02cbce5a90d9f6ea3be8787d37a7873bee29b0/src/fs_ext2.c#L205

**Comment by NabiKAZ** [comment]
As you said, I remove `-I 256` but still have problem, and the inode size was changed.

```
mke2fs /dev/sdb1  -q  -F  -b 4096  -L 'aaaaa'  -U 47849ac4-0cba-4fde-b7f0-0c22b159ad13  -r 1  -O has_journal,ext_attr,resize_inode,dir_index,^sparse_super2,filetype,extent,^journal_dev,flex_bg,^meta_bg,^mmp,64bit,^inline_data,^ea_inode,^large_dir,large_file,huge_file,sparse_super,^uninit_bg,dir_nlink,extra_isize,^bigalloc,metadata_csum,^project
```

**Comment by NabiKAZ** [comment]
Seem, The `extent` feature is for this goal!

As my test, in this normal code see at last the inode was changed:
```
mkfs -t ext4 -N 1000000 -F /dev/sdb1

mke2fs /dev/sdb1  -q  -F  -b 4096  -L 'aaaaa'  -U 47849ac4-0cba-4fde-b7f0-0c22b159ad13  -I 256  -r 1  -O has_journal,ext_attr,resize_inode,dir_index,^sparse_super2,filetype,extent,^journal_dev,flex_bg,^meta_bg,^mmp,64bit,^inline_data,^ea_inode,^large_dir,large_file,huge_file,sparse_super,^uninit_bg,dir_nlink,extra_isize,^bigalloc,metadata_csum,^project

tune2fs -l /dev/sdb1 | grep -i "inode count"

//Inode count:              64000
```

Now I disable this feature with `^extent`.
You can see at last the inodes keep in 1M.

```
mkfs -t ext4 -N 1000000 -F /dev/sdb1

mke2fs /dev/sdb1  -q  -F  -b 4096  -L 'aaaaa'  -U 47849ac4-0cba-4fde-b7f0-0c22b159ad13  -I 256  -r 1  -O has_journal,ext_attr,resize_inode,dir_index,^sparse_super2,filetype,^extent,^journal_dev,flex_bg,^meta_bg,^mmp,64bit,^inline_data,^ea_inode,^large_dir,large_file,huge_file,sparse_super,^uninit_bg,dir_nlink,extra_isize,^bigalloc,metadata_csum,^project

tune2fs -l /dev/sdb1 | grep -i "inode count"

//Inode count:              1000432
```

Do you suggestion me for just remove `extent` feature for my goal and this act don't appears any another problems?

**Comment by marcosfrm** [comment]
If you remove `extent` you basically downgrade the filesystem to EXT3.

You want to change the number of inodes. This is an advanced setting, calculated internally by `mke2fs` and fine tuned by the `-i` and `-N` options. IMHO, FSArchiver should not mess with them.

But move `mkfsopt` arguments latter in `mke2fs` invocation makes sense **if** in case of multiple occurrences of the same option the latest one wins, which is generally the case.

**Comment by NabiKAZ** [comment]
I have already changed the `inode` value by `mkfs`.
Now my problem is that when I restore the partition with `fsarchiver`, inode returns to its previous value and the reason is the use of `tune2fs`.
I just want to keep the previous value after `fsarchiver` restores the partition.
Now I understand by removing the `extent` feature. It happens.

Meanwhile, the partition remained `ext4` in the same way:
```/dev/sdb1      ext4      740M   16M  659M   3% /a```

**Comment by NabiKAZ** [comment]
Oh sorry, The last command in above without `extents` feature, will be returned error:
```
/dev/sdb1 contains a ext4 file system labelled 'aaaaa'
	created on Wed May  6 22:53:36 2020
Extents MUST be enabled for a 64-bit filesystem.  Pass -O extents to rectify.
```
So it don't works :-(

**Comment by marcosfrm** [comment]
The two options for what you want are `-i` and `-N`.

**Comment by NabiKAZ** [comment]
I try `-I 4096` in `mke2fs` but just will have 64000 inode.
And when use `-N` in `mkfs`, works good for any inode, But as I said, after use `fsarchiver`, will back to 64000

Can I express my problem correctly ?!

**Comment by NabiKAZ** [comment]
Oh! I understand now! Thanks @marcosfrm 

For a 500 GB disk, with about 50 million inodes, we have:

Block Size (`-b` in command) = 4096
Block count (in `tune2fs -l /dev/sdb1`) = 129447168
Partition Size = (Block Size * Block count) =  530215600128 ( ~500 GB )
inode_size (`-I` in command) = 256
inode_ratio (`-i` in command) = 10604
Max inodes = (Partition Size / inode_ratio) = 50003856

In fact, in other words, I divided 530215600128 by 50000000 to get the 10604 value for use in `-i` parameter.

So just should use this command:

```
fsarchiver restfs -v -j8 backup.fsa id=0,dest=/dev/sdb1,mkfsopt="-i 10604"
```

And finally the `mke2fs` command was be like this:

```
mke2fs /dev/sdb1  -q  -F  -i 10604  -b 4096  -L 'aaaaa'  -U 47849ac4-0cba-4fde-b7f0-0c22b159ad13  -I 256  -O ^has_journal,^ext_attr,^resize_inode,^dir_index,^sparse_super2,^filetype,extent,^journal_dev,^flex_bg,^meta_bg,^mmp,64bit,^inline_data,^ea_inode,^large_dir,^large_file,^huge_file,^sparse_super,^uninit_bg,^dir_nlink,^extra_isize,^bigalloc,^metadata_csum,^project
```

**Comment by marcosfrm** [comment]
@NabiKAZ 👏

> But move `mkfsopt` arguments latter in `mke2fs` invocation makes sense **if** in case of multiple occurrences of the same option the latest one wins, which is generally the case.

Added to my TODO.

**Comment by marcosfrm** [comment]
@NabiKAZ is this bug solved?

**Comment by NabiKAZ** [comment]
@marcosfrm Yes, As I said in latest post, I resolved the problem with add `,mkfsopt="-i 10604"`
Thanks for the good project.
