### ISSUE TITLE
ZFS support

### ISSUE THREAD

**Issue by fmitha** [fdupoux/fsarchiver#90]
I've used FSArchiver over many years, though not very often. Usually when doing a backup and restore for a new installation.

I just looked at the http://www.fsarchiver.org/partimage/ and ZFS is not mentioned. It's not mentioned elsewhere on the FSArchiver site either. I'm thinking of switching to ZFS at some point, and so I was wondering if ZFS is not supported, or the documentation just forgot to mention it.

If it is not supported, what is the problem, and is it possible support might arrive at some point?

**Comment by fdupoux** [comment]
No there is no plan to add support for ZFS. If you use ZFS you should consider using the send/receive tools instead.

**Comment by fmitha** [comment]
Thank you for the reply. Do you not provide support for ZFS, because ZFS has alternatives which make FSArchiver suppport unnecessary, or because it is too much work, or for some other reason?

**Comment by fdupoux** [comment]
ZFS does not work like other Linux file systems so it would be challenging to make it work, and fsarchiver would not understand ZFS features such as snapshots. Any there would be no real point as the send/receive tools are a much better way to backup/restore ZFS file systems. So it would be a lot of work for very little value.

**Comment by fmitha** [comment]
Ok. Thank you for the clarification.
