### ISSUE TITLE
New stable release

### ISSUE THREAD

**Issue by shumvgolove** [fdupoux/fsarchiver#93]
Most distributions target the latest stable release and latest `fsarchiver` has been issued ~2 years ago, maybe we can prepare a new one?

In particular, [an important fix was merged](https://github.com/fdupoux/fsarchiver/pull/92)  for musl-based distributions, which should fix [my issue.](https://github.com/fdupoux/fsarchiver/issues/91)

**Comment by marcosfrm** [comment]
It would be nice fix the part of #66 that makes FSArchiver get stuck. But I am afraid in touching the queue code and blowing things up. :-( @fdupoux is the guru in this area.

**Comment by fdupoux** [comment]
Can multiple users please test version 0.8.6-beta1 and confirm if it works fine so the final 0.8.6 can be released ?

Sources for this version can be found using the following link:
https://github.com/fdupoux/fsarchiver/releases/tag/0.8.6-beta1

**Comment by marcosfrm** [comment]
Working fine here.

**Comment by shumvgolove** [comment]
Sorry for the late reply. I was able to successfully build `fsarchiver-0.8.6-beta1` on Alpine Linux and indeed it's working correctly. 

```
$ doas fsarchiver restfs system_backup.fsa id=0,dest=/dev/loop0
Statistics for filesystem 0
* files successfully processed:....regfiles=1, directories=3, symlinks=0, hardlinks=0, specials=0
* files with errors:...............regfiles=0, directories=0, symlinks=0, hardlinks=0, specials=0
```

**Comment by fdupoux** [comment]
Thanks for testing. Version 0.8.6 has been released
