### ISSUE TITLE
[REQUEST]: Include Guix in Distributions List

### ISSUE THREAD

**Issue by raghavgururajan** [fdupoux/fsarchiver#95]
FSArchiver is now [available](https://git.savannah.gnu.org/cgit/guix.git/commit/?id=a54f373e6ec940e08b3fc95f2b5938429001976d) in [Guix](https://guix.gnu.org).
Please mention Guix in the home-page.
Also, please consider using the term GNU/Linux instead of just Linux.

**Comment by fdupoux** [comment]
The website has been updated
