### ISSUE TITLE
[REQUEST] Automated Restores

### ISSUE THREAD

**Issue by roysubs** [fdupoux/fsarchiver#97]
Looking at your excellent tool, I have a bit of a question / request about restores.

I have some servers that are remote and so backing up is fine, but what if I want to restore. I can't go to the server to plug in a USB stick to do an OS partition restore. On Windows, this is easy to do (various tools like Macrium Reflect make this super easy as they install an alternative boot loader, and load into that and then perform the restore, then reboot back into the restored OS) but I'm desperately looking for a tool that will allow me to do the same on Linux.

• Can your tool do this?

• Might there be a project that offers functionality like this that you know of (i.e. reboot into an alternative OS, run a task, then reboot back into the main OS)?

• Might this be something that you could consider on a future version of the tool?

I know this might be complex, but it would really be an amazing feature that that could be really worth (the ability to remotely restore a bare metal server back to a known backup as easily as a rolling back a VM would be so useful!).

**Comment by fdupoux** [comment]
You can use https://www.system-rescue.org/ which provides fsarchiver. You can either boot via PXE boot or install it to your local disk if you cannot use removable boot devices. It is easy to boot SystemRescue from Grub. You need to configure SystemRescue to set a root password and disable the firewall (via the boot command line) so you can connect remotely via SSH and then you can run fsarchiver. Or you can write an autorun script to run fsarchiver automatically.
