### ISSUE TITLE
Help with --exclude filter

### ISSUE THREAD

**Issue by linuxiano** [fdupoux/fsarchiver#98]
Hi,
first, thanks for your great app!

I'm learning fsarchiver within SystemRescue CD. It uses Arch Linux (Bash terminal).

I'm in a trouble with the _--exclude_ filter to work.
My command is:
`fsarchiver savefs -o "/path/191120.fsa" /dev/sda2 /dev/sda3 -v -j2 -Z9 --exclude="/cache2/entries/*" --exclude="/var/cache/pacman/pkg/*" --exclude="/baloo/*"`

The first _exclude_ filter     
"/cache2/entries/*" doesn't seem to work (it is the firefox cache in ./.cache/mozilla/firefox/3fw5bqse.default-esr/cache2/entries/).
I'd like to exclude every files in the '**entries**' directory.
The others --exclude filters seem ok.

The first question: I have to put the absolute path? I wouldn't use the absolute path, because the firefox number in the profile change at every system.
The fsarchiver help shows:
>  * save a filesystem and exclude all files/dirs called 'pagefile.*':
>    fsarchiver savefs /data/myarchive.fsa /dev/sda1 --exclude='pagefile.*'
>  * generic exclude for 'share' such as '/usr/share' and '/usr/local/share':
>    fsarchiver savefs /data/myarchive.fsa --exclude=share
>  * absolute exclude valid for '/usr/share' but not for '/usr/local/share':
>    fsarchiver savefs /data/myarchive.fsa --exclude=/usr/share

The second question: How can I check which files are put from fsarchiver in the archive?

The third question: I tried to redirect the fsarchiver archinfo output to a file with:
`fsarchiver archinfo /path/191120.fsa | tee /mnt/bk-data/Backups/fsarchiver/fsa.log` or 
`fsarchiver archinfo /path/191120.fsa >> /mnt/bk-data/Backups/fsarchiver/fsa.log` 
`fsarchiver archinfo /path/191120.fsa 1>> /mnt/bk-data/Backups/fsarchiver/fsa.log` 
but it doesn't work. The file log is empty.
In Terminal is ok.

Any ideas? Thanks in advance.

**Comment by marcosfrm** [comment]
Use single quotes (`'`).

`archinfo` output goes to stderr if i remember correctly. So redirect everything: `fsarchiver archinfo ... &> ...`

**Comment by neitsab** [comment]
Hi, please allow me to chime in. I found the thread as I was looking for info on using fsarchiver exclude filter after the following variations didn't work:

```
--exclude=cache/pacman
--exclude='cache/pacman/pkg'
--exclude='/var/cache/pacman/pkg/*'
--exclude="var/cache/pacman/pkg/*"
--exclude='/pacman/pkg/'
--exclude='pacman/pkg/'
--exclude='pacman/pkg/*' 
```

What worked (but is not really suitable):

    --exclude=cache
    --exclude='*.pkg.tar.zst'

This is in the context of a `savedir` operation from the latest  `archlinux-2022.02.01-x86_64.iso` with fsarchiver version 0.8.6 (2021-02-27). Complete command:

    root@archiso ~ # fsarchiver -Z3 -j$(nproc) -v savedir /tmp/test.fsa --exclude=<pattern> /mnt/var/

**What finally worked was** (single or double quotes irrelevant):

    fsarchiver -Z3 -j$(nproc) -v savedir /tmp/test.fsa --exclude="/mnt/var/cache/pacman/pkg/*" /mnt/var/
    (same as)
    fsarchiver -Z3 -j$(nproc) -v savedir /tmp/test.fsa /mnt/var/ --exclude='/mnt/var/cache/pacman/pkg/*'

It doesn't work without the wildcard **if** we keep the trailing slash (type of quoting not relevant):

    fsarchiver -Z3 -j$(nproc) -v savedir /tmp/test.fsa --exclude="/mnt/var/cache/pacman/pkg/" /mnt/var/
    fsarchiver -Z3 -j$(nproc) -v savedir /tmp/test.fsa --exclude='/mnt/var/cache/pacman/pkg/' /mnt/var/

However it works again if we remove the trailing `/` (again, quoting irrelevant)

    fsarchiver -Z3 -j$(nproc) -v savedir /tmp/test.fsa --exclude="/mnt/var/cache/pacman/pkg" /mnt/var/

Could you please clarify the rules for the exclude patterns on fsarchiver website/manpage? From what I gathered, iat least n `savedir` mode:

* using the absolute path seems required
* and either `/*` (directory's content) or "no trailing slash" (directory itself) is required; a trailing slash will invalidate the pattern.

Thank you!
