### ISSUE TITLE
Extracting files/dirs from fsa

### ISSUE THREAD

**Issue by orangebutblue** [fdupoux/fsarchiver#99]
Is there a way to extract just a single file or folder from an fs archive?

I've been running daily backups for months now and I simply want to restore a single accidentally deleted file from an archive.  How can I do that?

I don't want to restore gigabytes of data and overwrite everything when I just need a single file.

**Comment by TheWiresharkGuy** [comment]
No but you can use this guide to mount an archive into a loop filesystem and restore only the files you need

https://eeknay.github.io/2013/07/18/fsarchiver/
